### ISSUE TITLE
bug with the useables that move you

### ISSUE THREAD

**Issue by whichtwix** [XtraCube/SmolMod#1]
- with any scale thats not 1, if you use the zipline on fungle it takes you out of boundaries of the map and you cant return 
- on airship a scale of 2.2 or above makes it impossible to use the platform or ladder

**Comment by XtraCube** [comment]
Thank you for testing, I am currently working on fixes

**Comment by XtraCube** [comment]
fixed ziplines with b5d5fe14d734ef6a21be8101a706bbc47230fb4d

**Comment by XtraCube** [comment]
Wait forgot about airship

**Comment by XtraCube** [comment]
Airship issues should be resolved as of 0ee7952208b97a864c0fce2e70d8e403646c7657
